updated readme.md
adhikariraju38/marketplace pull request #1
Opened 2024-04-08 05:15 UTC by prashant676a

2024-04-08 05:20 UTC, rockerritesh requested changes

2024-04-08 05:20 UTC, rockerritesh commented on README.md
> +
Add contributor name

2024-04-08 05:21 UTC, rockerritesh commented on README.md
> +
@prashant676a use `imperative sentence`  for commit message

2024-04-08 13:26 UTC, merged

2024-04-09 01:45 UTC, prashant676a commented
@rockerritesh done all things you've mentioned. Thanks